[
    {
        "host": "51.38.114.131",
        "port": 22003,
        "type": "mtasa",
        "appId": 0,
        "discord": {
            "channelIds": ["962237013652799528" , "962283926930485248"]
        },
        "telegram": {
            "chatIds": []
        }
    }
]
